version: '2'
services:
  control:
    build:
      context: .
      dockerfile: ./control/Dockerfile
    restart: always
    privileged: true
    expose:
      - "80"
      - "2112"
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    restart: always
    volumes:
      - 'grafana-data:/var/lib/grafana'
  tailscale:
    image: tailscale/tailscale
    restart: always
    environment:
      - TS_USERSPACE=true
    network_mode: host
    volumes:
      - 'tailscale-data:/var/lib'
volumes:
  grafana-data:
  tailscale-data: