version: '2'
services:
  control:
    build:
      context: .
      dockerfile: ./control/Dockerfile
    restart: always
    privileged: true
    expose:
      - "80"
      - "2112"
  agent:
    build:
      context: .
      dockerfile: ./agent/Dockerfile
    restart: always
    volumes:
      - 'grafana-data:/var/lib/grafana'
  tailscale:
    image: tailscale/tailscale
    restart: always
    network_mode: host
    privileged: true
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
volumes:
  grafana-data: