// Code generated by protoc-gen-go. DO NOT EDIT.
// source: telemetry.proto

/*
Package telemetry is a generated protocol buffer package.

It is generated from these files:
	telemetry.proto

It has these top-level messages:
	TelemetryMessage
*/
package telemetry

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type TelemetryMessage struct {
	Name        string  `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Temperature float64 `protobuf:"fixed64,2,opt,name=temperature" json:"temperature,omitempty"`
	On          bool    `protobuf:"varint,3,opt,name=on" json:"on,omitempty"`
}

func (m *TelemetryMessage) Reset()                    { *m = TelemetryMessage{} }
func (m *TelemetryMessage) String() string            { return proto.CompactTextString(m) }
func (*TelemetryMessage) ProtoMessage()               {}
func (*TelemetryMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TelemetryMessage) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TelemetryMessage) GetTemperature() float64 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *TelemetryMessage) GetOn() bool {
	if m != nil {
		return m.On
	}
	return false
}

func init() {
	proto.RegisterType((*TelemetryMessage)(nil), "telemetry.TelemetryMessage")
}

func init() { proto.RegisterFile("telemetry.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 121 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0xcd, 0x49,
	0xcd, 0x4d, 0x2d, 0x29, 0xaa, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x45, 0x70, 0x09, 0x84, 0xc0, 0x38, 0xbe, 0xa9, 0xc5, 0xc5, 0x89, 0xe9, 0xa9, 0x42, 0x42, 0x5c,
	0x2c, 0x79, 0x89, 0xb9, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x60, 0xb6, 0x90, 0x02,
	0x17, 0x77, 0x49, 0x6a, 0x6e, 0x41, 0x6a, 0x51, 0x62, 0x49, 0x69, 0x51, 0xaa, 0x04, 0x93, 0x02,
	0xa3, 0x06, 0x63, 0x10, 0xb2, 0x90, 0x10, 0x1f, 0x17, 0x53, 0x7e, 0x9e, 0x04, 0xb3, 0x02, 0xa3,
	0x06, 0x47, 0x10, 0x53, 0x7e, 0x5e, 0x12, 0x1b, 0xd8, 0x2e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x7f, 0xaf, 0x41, 0xa3, 0x7e, 0x00, 0x00, 0x00,
}
