room {
  name: "Study"
  target_temperature: 20
  radiator {
    address: "\x2e\x04"
  }
  schedule {
    interval {
      begin {
        hour: 15
        minute: 0
      }
      end {
        hour: 23
        minute: 59
      }
      type: ON
    }
  }
}
room {
  name: "Living Room"
  target_temperature: 20
  radiator {
    address: "\x2b\xdb"
  }
}
room {
  name: "Bedroom"
  target_temperature: 17
  radiator {
    address: "\x2b\x76"
  }
  schedule {
    interval {
      begin {
        hour: 9
        minute: 0
      }
      end {
        hour: 11
        minute: 0
      }
      type: ON
    }
  }
}
room {
  name: "Hall"
  target_temperature: 17
  radiator {
    address: "\x2c\x2c"
  }
}
