zone {
  name: "Study"
  radiator {
    address: "\x2e\x04"
  }
  calendar_id: "rf0m8vm1skp5nhjp4eg0q0imdk@group.calendar.google.com"
  target_temperature: 20
}
zone {
  name: "Living Room"
  radiator {
    address: "\x2b\xdb"
  }
  radiator {
    address: "\x2b\xdc"
  }
  calendar_id: "p6j07ks29qfh5fdnu7s9mo321c@group.calendar.google.com"
  target_temperature: 20
}
zone {
  name: "Bedroom"
  radiator {
    address: "\x2b\x76"
  }
  calendar_id: "oep295difakq4tt8a48of6q724@group.calendar.google.com"
  target_temperature: 18
}
zone {
  name: "Hall"
  radiator {
    address: "\x2c\x2c"
  }
  calendar_id: "gb0gp6h4ti4ocl4sas5c1jqou4@group.calendar.google.com"
  target_temperature: 15
}
