package config

// Rf settings for CC1101
const (
    IOCFG2 = 0x29         // GDO2 Output Pin Configuration
    IOCFG1 = 0x2e         // GDO1 Output Pin Configuration
    IOCFG0 = 0x07         // GDO0 Output Pin Configuration
    FIFOTHR = 0x47        // RX FIFO and TX FIFO Thresholds
    SYNC1 = 0xd3          // Sync Word, High Byte
    SYNC0 = 0x91          // Sync Word, Low Byte
    PKTLEN = 0x3d         // Packet Length
    PKTCTRL1 = 0x04       // Packet Automation Control
    PKTCTRL0 = 0x05       // Packet Automation Control
    ADDR = 0x00           // Device Address
    CHANNR = 0x00         // Channel Number
    FSCTRL1 = 0x06        // Frequency Synthesizer Control
    FSCTRL0 = 0x00        // Frequency Synthesizer Control
    FREQ2 = 0x21          // Frequency Control Word, High Byte
    FREQ1 = 0x65          // Frequency Control Word, Middle Byte
    FREQ0 = 0x44          // Frequency Control Word, Low Byte
    MDMCFG4 = 0xf5        // Modem Configuration
    MDMCFG3 = 0x83        // Modem Configuration
    MDMCFG2 = 0x03        // Modem Configuration
    MDMCFG1 = 0x22        // Modem Configuration
    MDMCFG0 = 0xf8        // Modem Configuration
    DEVIATN = 0x34        // Modem Deviation Setting
    MCSM2 = 0x07          // Main Radio Control State Machine Configuration
    MCSM1 = 0x30          // Main Radio Control State Machine Configuration
    MCSM0 = 0x18          // Main Radio Control State Machine Configuration
    FOCCFG = 0x16         // Frequency Offset Compensation Configuration
    BSCFG = 0x6c          // Bit Synchronization Configuration
    AGCCTRL2 = 0x03       // AGC Control
    AGCCTRL1 = 0x40       // AGC Control
    AGCCTRL0 = 0x91       // AGC Control
    WOREVT1 = 0x87        // High Byte Event0 Timeout
    WOREVT0 = 0x6b        // Low Byte Event0 Timeout
    WORCTRL = 0xfb        // Wake On Radio Control
    FREND1 = 0x56         // Front End RX Configuration
    FREND0 = 0x10         // Front End TX Configuration
    FSCAL3 = 0xe9         // Frequency Synthesizer Calibration
    FSCAL2 = 0x2a         // Frequency Synthesizer Calibration
    FSCAL1 = 0x00         // Frequency Synthesizer Calibration
    FSCAL0 = 0x1f         // Frequency Synthesizer Calibration
    RCCTRL1 = 0x41        // RC Oscillator Configuration
    RCCTRL0 = 0x00        // RC Oscillator Configuration
    FSTEST = 0x59         // Frequency Synthesizer Calibration Control
    PTEST = 0x7f          // Production Test
    AGCTEST = 0x3f        // AGC Test
    TEST2 = 0x81          // Various Test Settings
    TEST1 = 0x35          // Various Test Settings
    TEST0 = 0x09          // Various Test Settings
    PARTNUM = 0x00        // Chip ID
    VERSION = 0x04        // Chip ID
    FREQEST = 0x00        // Frequency Offset Estimate from Demodulator
    LQI = 0x00            // Demodulator Estimate for Link Quality
    RSSI = 0x00           // Received Signal Strength Indication
    MARCSTATE = 0x00      // Main Radio Control State Machine State
    WORTIME1 = 0x00       // High Byte of WOR Time
    WORTIME0 = 0x00       // Low Byte of WOR Time
    PKTSTATUS = 0x00      // Current GDOx Status and Packet Status
    VCO_VC_DAC = 0x00     // Current Setting from PLL Calibration Module
    TXBYTES = 0x00        // Underflow and Number of Bytes
    RXBYTES = 0x00        // Overflow and Number of Bytes
    RCCTRL1_STATUS = 0x00 // Last RC Oscillator Calibration Result
    RCCTRL0_STATUS = 0x00 // Last RC Oscillator Calibration Result
)
