// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	control.proto
	service.proto

It has these top-level messages:
	Radiator
	Zone
	GetZonesRequest
	GetZonesReply
	GetZoneStatusRequest
	GetZoneStatusReply
	SetZoneScheduleRequest
	SetZoneScheduleReply
	Config
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Radiator struct {
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *Radiator) Reset()                    { *m = Radiator{} }
func (m *Radiator) String() string            { return proto.CompactTextString(m) }
func (*Radiator) ProtoMessage()               {}
func (*Radiator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Radiator) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func init() {
	proto.RegisterType((*Radiator)(nil), "control.Radiator")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 80 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2b,
	0x29, 0xca, 0xcf, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x87, 0x72, 0x95, 0x54, 0xb8,
	0x38, 0x82, 0x12, 0x53, 0x32, 0x13, 0x4b, 0xf2, 0x8b, 0x84, 0x24, 0xb8, 0xd8, 0x13, 0x53, 0x52,
	0x8a, 0x52, 0x8b, 0x8b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x78, 0x82, 0x60, 0xdc, 0x24, 0x36, 0xb0,
	0x2e, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xf8, 0xad, 0x0e, 0x63, 0x46, 0x00, 0x00, 0x00,
}
