// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	control.proto

It has these top-level messages:
	Radiator
	Sensor
	Room
	Config
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Radiator struct {
	Address          []byte `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Radiator) Reset()                    { *m = Radiator{} }
func (m *Radiator) String() string            { return proto.CompactTextString(m) }
func (*Radiator) ProtoMessage()               {}
func (*Radiator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Radiator) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Sensor struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Sensor) Reset()                    { *m = Sensor{} }
func (m *Sensor) String() string            { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()               {}
func (*Sensor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Room struct {
	Sensor            *Sensor   `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
	Radiator          *Radiator `protobuf:"bytes,2,opt,name=radiator" json:"radiator,omitempty"`
	Name              *string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	TargetTemperature *int32    `protobuf:"varint,4,opt,name=target_temperature" json:"target_temperature,omitempty"`
	XXX_unrecognized  []byte    `json:"-"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Room) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Room) GetRadiator() *Radiator {
	if m != nil {
		return m.Radiator
	}
	return nil
}

func (m *Room) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Room) GetTargetTemperature() int32 {
	if m != nil && m.TargetTemperature != nil {
		return *m.TargetTemperature
	}
	return 0
}

type Config struct {
	Room             []*Room `protobuf:"bytes,1,rep,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Config) GetRoom() []*Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*Radiator)(nil), "control.Radiator")
	proto.RegisterType((*Sensor)(nil), "control.Sensor")
	proto.RegisterType((*Room)(nil), "control.Room")
	proto.RegisterType((*Config)(nil), "control.Config")
}

func init() { proto.RegisterFile("control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 186 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xcd, 0xc1, 0x6a, 0x84, 0x30,
	0x10, 0xc6, 0x71, 0x52, 0x53, 0xb5, 0xa3, 0x22, 0xcd, 0x29, 0xd4, 0x43, 0x43, 0x4a, 0x21, 0x27,
	0x0f, 0xbe, 0x42, 0xdf, 0xc0, 0x3e, 0x40, 0x09, 0x35, 0x2b, 0xc2, 0x26, 0x23, 0x93, 0xec, 0x3e,
	0xff, 0x82, 0xeb, 0xba, 0xc7, 0x19, 0x7e, 0xfc, 0x3f, 0x68, 0xfe, 0x31, 0x24, 0xc2, 0x73, 0xbf,
	0x12, 0x26, 0x14, 0xc5, 0x7e, 0xea, 0x0e, 0xca, 0xd1, 0x4e, 0x8b, 0x4d, 0x48, 0xa2, 0x85, 0xc2,
	0x4e, 0x13, 0xb9, 0x18, 0x25, 0x53, 0xcc, 0xd4, 0xba, 0x84, 0xfc, 0xd7, 0x85, 0x88, 0xa4, 0xaf,
	0xc0, 0x47, 0x44, 0x2f, 0x3e, 0x21, 0x8f, 0xdb, 0x67, 0x13, 0xd5, 0xd0, 0xf6, 0x8f, 0xee, 0x1d,
	0x8a, 0x2f, 0x28, 0x69, 0xef, 0xc9, 0x97, 0x8d, 0xbc, 0x1f, 0xe4, 0x18, 0xaa, 0x81, 0x07, 0xeb,
	0x9d, 0xcc, 0x14, 0x33, 0x6f, 0xe2, 0x03, 0x44, 0xb2, 0x34, 0xbb, 0xf4, 0x97, 0x9c, 0x5f, 0x1d,
	0xd9, 0x74, 0x21, 0x27, 0xb9, 0x62, 0xe6, 0x55, 0x7f, 0x43, 0xfe, 0x83, 0xe1, 0xb4, 0xcc, 0xa2,
	0x03, 0x4e, 0x88, 0x5e, 0x32, 0x95, 0x99, 0x6a, 0x68, 0x9e, 0x51, 0x44, 0x7f, 0x0b, 0x00, 0x00,
	0xff, 0xff, 0x01, 0xb8, 0x27, 0x15, 0xde, 0x00, 0x00, 0x00,
}
