// Code generated by protoc-gen-go. DO NOT EDIT.
// source: control.proto

/*
Package control is a generated protocol buffer package.

It is generated from these files:
	control.proto

It has these top-level messages:
	Radiator
	Sensor
	Schedule
	Room
	Config
*/
package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Schedule_Change_ChangeType int32

const (
	Schedule_Change_UNKNOWN Schedule_Change_ChangeType = 0
	Schedule_Change_OFF     Schedule_Change_ChangeType = 1
	Schedule_Change_ON      Schedule_Change_ChangeType = 2
)

var Schedule_Change_ChangeType_name = map[int32]string{
	0: "UNKNOWN",
	1: "OFF",
	2: "ON",
}
var Schedule_Change_ChangeType_value = map[string]int32{
	"UNKNOWN": 0,
	"OFF":     1,
	"ON":      2,
}

func (x Schedule_Change_ChangeType) Enum() *Schedule_Change_ChangeType {
	p := new(Schedule_Change_ChangeType)
	*p = x
	return p
}
func (x Schedule_Change_ChangeType) String() string {
	return proto.EnumName(Schedule_Change_ChangeType_name, int32(x))
}
func (x *Schedule_Change_ChangeType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Schedule_Change_ChangeType_value, data, "Schedule_Change_ChangeType")
	if err != nil {
		return err
	}
	*x = Schedule_Change_ChangeType(value)
	return nil
}
func (Schedule_Change_ChangeType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2, 1, 0}
}

type Radiator struct {
	Address          []byte `protobuf:"bytes,1,opt,name=address" json:"address,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Radiator) Reset()                    { *m = Radiator{} }
func (m *Radiator) String() string            { return proto.CompactTextString(m) }
func (*Radiator) ProtoMessage()               {}
func (*Radiator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Radiator) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

type Sensor struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *Sensor) Reset()                    { *m = Sensor{} }
func (m *Sensor) String() string            { return proto.CompactTextString(m) }
func (*Sensor) ProtoMessage()               {}
func (*Sensor) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Schedule struct {
	Change           []*Schedule_Change `protobuf:"bytes,1,rep,name=change" json:"change,omitempty"`
	XXX_unrecognized []byte             `json:"-"`
}

func (m *Schedule) Reset()                    { *m = Schedule{} }
func (m *Schedule) String() string            { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()               {}
func (*Schedule) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Schedule) GetChange() []*Schedule_Change {
	if m != nil {
		return m.Change
	}
	return nil
}

type Schedule_Time struct {
	Hour             *int32 `protobuf:"varint,1,opt,name=hour" json:"hour,omitempty"`
	Minute           *int32 `protobuf:"varint,2,opt,name=minute" json:"minute,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *Schedule_Time) Reset()                    { *m = Schedule_Time{} }
func (m *Schedule_Time) String() string            { return proto.CompactTextString(m) }
func (*Schedule_Time) ProtoMessage()               {}
func (*Schedule_Time) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *Schedule_Time) GetHour() int32 {
	if m != nil && m.Hour != nil {
		return *m.Hour
	}
	return 0
}

func (m *Schedule_Time) GetMinute() int32 {
	if m != nil && m.Minute != nil {
		return *m.Minute
	}
	return 0
}

type Schedule_Change struct {
	Time             *Schedule_Time              `protobuf:"bytes,1,opt,name=time" json:"time,omitempty"`
	Type             *Schedule_Change_ChangeType `protobuf:"varint,2,opt,name=type,enum=control.Schedule_Change_ChangeType" json:"type,omitempty"`
	XXX_unrecognized []byte                      `json:"-"`
}

func (m *Schedule_Change) Reset()                    { *m = Schedule_Change{} }
func (m *Schedule_Change) String() string            { return proto.CompactTextString(m) }
func (*Schedule_Change) ProtoMessage()               {}
func (*Schedule_Change) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *Schedule_Change) GetTime() *Schedule_Time {
	if m != nil {
		return m.Time
	}
	return nil
}

func (m *Schedule_Change) GetType() Schedule_Change_ChangeType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Schedule_Change_UNKNOWN
}

type Room struct {
	Sensor            *Sensor   `protobuf:"bytes,1,opt,name=sensor" json:"sensor,omitempty"`
	Radiator          *Radiator `protobuf:"bytes,2,opt,name=radiator" json:"radiator,omitempty"`
	Name              *string   `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	TargetTemperature *int32    `protobuf:"varint,4,opt,name=target_temperature" json:"target_temperature,omitempty"`
	Schedule          *Schedule `protobuf:"bytes,5,opt,name=schedule" json:"schedule,omitempty"`
	XXX_unrecognized  []byte    `json:"-"`
}

func (m *Room) Reset()                    { *m = Room{} }
func (m *Room) String() string            { return proto.CompactTextString(m) }
func (*Room) ProtoMessage()               {}
func (*Room) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Room) GetSensor() *Sensor {
	if m != nil {
		return m.Sensor
	}
	return nil
}

func (m *Room) GetRadiator() *Radiator {
	if m != nil {
		return m.Radiator
	}
	return nil
}

func (m *Room) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

func (m *Room) GetTargetTemperature() int32 {
	if m != nil && m.TargetTemperature != nil {
		return *m.TargetTemperature
	}
	return 0
}

func (m *Room) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type Config struct {
	Room             []*Room `protobuf:"bytes,1,rep,name=room" json:"room,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Config) GetRoom() []*Room {
	if m != nil {
		return m.Room
	}
	return nil
}

func init() {
	proto.RegisterType((*Radiator)(nil), "control.Radiator")
	proto.RegisterType((*Sensor)(nil), "control.Sensor")
	proto.RegisterType((*Schedule)(nil), "control.Schedule")
	proto.RegisterType((*Schedule_Time)(nil), "control.Schedule.Time")
	proto.RegisterType((*Schedule_Change)(nil), "control.Schedule.Change")
	proto.RegisterType((*Room)(nil), "control.Room")
	proto.RegisterType((*Config)(nil), "control.Config")
	proto.RegisterEnum("control.Schedule_Change_ChangeType", Schedule_Change_ChangeType_name, Schedule_Change_ChangeType_value)
}

func init() { proto.RegisterFile("control.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x6b, 0xea, 0x40,
	0x14, 0x7d, 0xa3, 0x63, 0x92, 0x77, 0xe3, 0xd7, 0xbb, 0x8b, 0x47, 0xd0, 0xc5, 0x93, 0xe8, 0x83,
	0xd0, 0x85, 0xd0, 0xfc, 0x05, 0xc1, 0x4d, 0x21, 0x82, 0x5a, 0xba, 0x2c, 0xc1, 0xdc, 0x6a, 0xc0,
	0xc9, 0x0d, 0x93, 0xc9, 0xc2, 0x1f, 0xd1, 0x5f, 0xd0, 0x7f, 0xd8, 0x5f, 0x51, 0x3a, 0x46, 0x85,
	0x96, 0xae, 0x86, 0x33, 0x73, 0xee, 0x39, 0xf7, 0x9c, 0x81, 0xde, 0x8e, 0x0b, 0xa3, 0xf9, 0x38,
	0x2f, 0x35, 0x1b, 0x46, 0xb7, 0x81, 0xe1, 0x18, 0xbc, 0x75, 0x9a, 0xe5, 0xa9, 0x61, 0x8d, 0x03,
	0x70, 0xd3, 0x2c, 0xd3, 0x54, 0x55, 0x81, 0x98, 0x88, 0xa8, 0x1b, 0x7a, 0xe0, 0x6c, 0xa8, 0xa8,
	0x58, 0x87, 0xef, 0x02, 0xbc, 0xcd, 0xee, 0x40, 0x59, 0x7d, 0x24, 0x8c, 0xc0, 0xd9, 0x1d, 0xd2,
	0x62, 0x4f, 0x81, 0x98, 0xb4, 0x23, 0x3f, 0x0e, 0xe6, 0x17, 0xf1, 0x0b, 0x65, 0xbe, 0xb0, 0xef,
	0xa3, 0x19, 0xc8, 0x6d, 0xae, 0x08, 0xbb, 0x20, 0x0f, 0x5c, 0x6b, 0x2b, 0xdb, 0xc1, 0x3e, 0x38,
	0x2a, 0x2f, 0x6a, 0x43, 0x41, 0xeb, 0x13, 0x8f, 0x5e, 0x05, 0x38, 0xe7, 0x01, 0x9c, 0x81, 0x34,
	0xb9, 0x22, 0x4b, 0xf4, 0xe3, 0xbf, 0xdf, 0x85, 0xad, 0xdc, 0x3d, 0x48, 0x73, 0x2a, 0xcf, 0xe3,
	0xfd, 0x78, 0xfa, 0x93, 0x7d, 0x73, 0x6c, 0x4f, 0x25, 0x85, 0x77, 0x00, 0x37, 0x84, 0x3e, 0xb8,
	0x8f, 0xc9, 0x43, 0xb2, 0x7a, 0x4a, 0x86, 0xbf, 0xd0, 0x85, 0xf6, 0x6a, 0xb9, 0x1c, 0x0a, 0x74,
	0xa0, 0xb5, 0x4a, 0x86, 0xad, 0xf0, 0x4d, 0x80, 0x5c, 0x33, 0x2b, 0xfc, 0x07, 0x4e, 0x65, 0xf3,
	0x37, 0xfb, 0x0c, 0x6e, 0x4e, 0xf6, 0x1a, 0xa7, 0xe0, 0xe9, 0xa6, 0x3d, 0xbb, 0x8c, 0x1f, 0xff,
	0xb9, 0x52, 0xae, 0xb5, 0x76, 0x41, 0x16, 0xa9, 0xa2, 0xa0, 0x3d, 0x11, 0xd1, 0x6f, 0x1c, 0x01,
	0x9a, 0x54, 0xef, 0xc9, 0x3c, 0x1b, 0x52, 0x25, 0xe9, 0xd4, 0xd4, 0x9a, 0x02, 0x69, 0x8b, 0x99,
	0x82, 0x57, 0x35, 0x11, 0x82, 0xce, 0x17, 0xb9, 0x4b, 0xb6, 0xf0, 0x3f, 0x38, 0x0b, 0x2e, 0x5e,
	0xf2, 0x3d, 0x8e, 0x41, 0x6a, 0x66, 0xd5, 0xfc, 0x42, 0xef, 0xe6, 0xcc, 0xac, 0x3e, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x81, 0xab, 0xb4, 0xf6, 0xf1, 0x01, 0x00, 0x00,
}
