// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package control

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type HeatingState int32

const (
	HeatingState_UNKNOWN HeatingState = 0
	HeatingState_ON      HeatingState = 1
	HeatingState_OFF     HeatingState = 2
)

var HeatingState_name = map[int32]string{
	0: "UNKNOWN",
	1: "ON",
	2: "OFF",
}
var HeatingState_value = map[string]int32{
	"UNKNOWN": 0,
	"ON":      1,
	"OFF":     2,
}

func (x HeatingState) String() string {
	return proto.EnumName(HeatingState_name, int32(x))
}
func (HeatingState) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type Zone struct {
	Name     string      `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Radiator []*Radiator `protobuf:"bytes,2,rep,name=radiator" json:"radiator,omitempty"`
	Schedule *Schedule   `protobuf:"bytes,3,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *Zone) Reset()                    { *m = Zone{} }
func (m *Zone) String() string            { return proto.CompactTextString(m) }
func (*Zone) ProtoMessage()               {}
func (*Zone) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Zone) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Zone) GetRadiator() []*Radiator {
	if m != nil {
		return m.Radiator
	}
	return nil
}

func (m *Zone) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type GetZonesRequest struct {
}

func (m *GetZonesRequest) Reset()                    { *m = GetZonesRequest{} }
func (m *GetZonesRequest) String() string            { return proto.CompactTextString(m) }
func (*GetZonesRequest) ProtoMessage()               {}
func (*GetZonesRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type GetZonesReply struct {
	Zone []*Zone `protobuf:"bytes,1,rep,name=zone" json:"zone,omitempty"`
}

func (m *GetZonesReply) Reset()                    { *m = GetZonesReply{} }
func (m *GetZonesReply) String() string            { return proto.CompactTextString(m) }
func (*GetZonesReply) ProtoMessage()               {}
func (*GetZonesReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *GetZonesReply) GetZone() []*Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

type GetZoneStatusRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *GetZoneStatusRequest) Reset()                    { *m = GetZoneStatusRequest{} }
func (m *GetZoneStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*GetZoneStatusRequest) ProtoMessage()               {}
func (*GetZoneStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *GetZoneStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetZoneStatusReply struct {
	Name               string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	TargetTemperature  float32      `protobuf:"fixed32,2,opt,name=target_temperature,json=targetTemperature" json:"target_temperature,omitempty"`
	CurrentTemperature float32      `protobuf:"fixed32,3,opt,name=current_temperature,json=currentTemperature" json:"current_temperature,omitempty"`
	State              HeatingState `protobuf:"varint,4,opt,name=state,enum=control.HeatingState" json:"state,omitempty"`
	Schedule           *Schedule    `protobuf:"bytes,5,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *GetZoneStatusReply) Reset()                    { *m = GetZoneStatusReply{} }
func (m *GetZoneStatusReply) String() string            { return proto.CompactTextString(m) }
func (*GetZoneStatusReply) ProtoMessage()               {}
func (*GetZoneStatusReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *GetZoneStatusReply) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetZoneStatusReply) GetTargetTemperature() float32 {
	if m != nil {
		return m.TargetTemperature
	}
	return 0
}

func (m *GetZoneStatusReply) GetCurrentTemperature() float32 {
	if m != nil {
		return m.CurrentTemperature
	}
	return 0
}

func (m *GetZoneStatusReply) GetState() HeatingState {
	if m != nil {
		return m.State
	}
	return HeatingState_UNKNOWN
}

func (m *GetZoneStatusReply) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type SetZoneScheduleRequest struct {
	Schedule *Schedule `protobuf:"bytes,1,opt,name=schedule" json:"schedule,omitempty"`
}

func (m *SetZoneScheduleRequest) Reset()                    { *m = SetZoneScheduleRequest{} }
func (m *SetZoneScheduleRequest) String() string            { return proto.CompactTextString(m) }
func (*SetZoneScheduleRequest) ProtoMessage()               {}
func (*SetZoneScheduleRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *SetZoneScheduleRequest) GetSchedule() *Schedule {
	if m != nil {
		return m.Schedule
	}
	return nil
}

type SetZoneScheduleReply struct {
}

func (m *SetZoneScheduleReply) Reset()                    { *m = SetZoneScheduleReply{} }
func (m *SetZoneScheduleReply) String() string            { return proto.CompactTextString(m) }
func (*SetZoneScheduleReply) ProtoMessage()               {}
func (*SetZoneScheduleReply) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

type Config struct {
	Zone []*Zone `protobuf:"bytes,1,rep,name=zone" json:"zone,omitempty"`
}

func (m *Config) Reset()                    { *m = Config{} }
func (m *Config) String() string            { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()               {}
func (*Config) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{7} }

func (m *Config) GetZone() []*Zone {
	if m != nil {
		return m.Zone
	}
	return nil
}

func init() {
	proto.RegisterType((*Zone)(nil), "control.Zone")
	proto.RegisterType((*GetZonesRequest)(nil), "control.GetZonesRequest")
	proto.RegisterType((*GetZonesReply)(nil), "control.GetZonesReply")
	proto.RegisterType((*GetZoneStatusRequest)(nil), "control.GetZoneStatusRequest")
	proto.RegisterType((*GetZoneStatusReply)(nil), "control.GetZoneStatusReply")
	proto.RegisterType((*SetZoneScheduleRequest)(nil), "control.SetZoneScheduleRequest")
	proto.RegisterType((*SetZoneScheduleReply)(nil), "control.SetZoneScheduleReply")
	proto.RegisterType((*Config)(nil), "control.Config")
	proto.RegisterEnum("control.HeatingState", HeatingState_name, HeatingState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for HeatingControlService service

type HeatingControlServiceClient interface {
	GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesReply, error)
	GetZoneStatus(ctx context.Context, in *GetZoneStatusRequest, opts ...grpc.CallOption) (*GetZoneStatusReply, error)
	SetZoneSchedule(ctx context.Context, in *SetZoneScheduleRequest, opts ...grpc.CallOption) (*SetZoneScheduleReply, error)
}

type heatingControlServiceClient struct {
	cc *grpc.ClientConn
}

func NewHeatingControlServiceClient(cc *grpc.ClientConn) HeatingControlServiceClient {
	return &heatingControlServiceClient{cc}
}

func (c *heatingControlServiceClient) GetZones(ctx context.Context, in *GetZonesRequest, opts ...grpc.CallOption) (*GetZonesReply, error) {
	out := new(GetZonesReply)
	err := grpc.Invoke(ctx, "/control.HeatingControlService/GetZones", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heatingControlServiceClient) GetZoneStatus(ctx context.Context, in *GetZoneStatusRequest, opts ...grpc.CallOption) (*GetZoneStatusReply, error) {
	out := new(GetZoneStatusReply)
	err := grpc.Invoke(ctx, "/control.HeatingControlService/GetZoneStatus", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *heatingControlServiceClient) SetZoneSchedule(ctx context.Context, in *SetZoneScheduleRequest, opts ...grpc.CallOption) (*SetZoneScheduleReply, error) {
	out := new(SetZoneScheduleReply)
	err := grpc.Invoke(ctx, "/control.HeatingControlService/SetZoneSchedule", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for HeatingControlService service

type HeatingControlServiceServer interface {
	GetZones(context.Context, *GetZonesRequest) (*GetZonesReply, error)
	GetZoneStatus(context.Context, *GetZoneStatusRequest) (*GetZoneStatusReply, error)
	SetZoneSchedule(context.Context, *SetZoneScheduleRequest) (*SetZoneScheduleReply, error)
}

func RegisterHeatingControlServiceServer(s *grpc.Server, srv HeatingControlServiceServer) {
	s.RegisterService(&_HeatingControlService_serviceDesc, srv)
}

func _HeatingControlService_GetZones_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZonesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeatingControlServiceServer).GetZones(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.HeatingControlService/GetZones",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeatingControlServiceServer).GetZones(ctx, req.(*GetZonesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeatingControlService_GetZoneStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetZoneStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeatingControlServiceServer).GetZoneStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.HeatingControlService/GetZoneStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeatingControlServiceServer).GetZoneStatus(ctx, req.(*GetZoneStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HeatingControlService_SetZoneSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetZoneScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HeatingControlServiceServer).SetZoneSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/control.HeatingControlService/SetZoneSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HeatingControlServiceServer).SetZoneSchedule(ctx, req.(*SetZoneScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _HeatingControlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "control.HeatingControlService",
	HandlerType: (*HeatingControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetZones",
			Handler:    _HeatingControlService_GetZones_Handler,
		},
		{
			MethodName: "GetZoneStatus",
			Handler:    _HeatingControlService_GetZoneStatus_Handler,
		},
		{
			MethodName: "SetZoneSchedule",
			Handler:    _HeatingControlService_SetZoneSchedule_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 476 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x93, 0x5b, 0x6e, 0xd3, 0x4e,
	0x14, 0xc6, 0x6b, 0x27, 0x4d, 0xda, 0x93, 0x7f, 0xfe, 0x89, 0x0f, 0x6d, 0xb0, 0x0c, 0x15, 0xc6,
	0x4f, 0x51, 0x0b, 0xb5, 0x08, 0x4b, 0xa8, 0xd4, 0x22, 0x21, 0x25, 0x92, 0x0d, 0x42, 0xe2, 0x05,
	0x0d, 0xc9, 0xc1, 0x58, 0x72, 0x67, 0xcc, 0x78, 0x5c, 0xd1, 0x22, 0x5e, 0xd8, 0x02, 0x4b, 0x60,
	0x49, 0x6c, 0xa1, 0x0b, 0x41, 0xe3, 0x5b, 0x2e, 0xa4, 0x2a, 0x6f, 0xd6, 0x7c, 0xdf, 0xfc, 0xce,
	0x65, 0x3e, 0x43, 0x3f, 0x23, 0x79, 0x15, 0xcf, 0xe9, 0x34, 0x95, 0x42, 0x09, 0xec, 0xce, 0x05,
	0x57, 0x52, 0x24, 0x4e, 0xbf, 0xfa, 0x28, 0xcf, 0x9d, 0xc7, 0x91, 0x10, 0x51, 0x42, 0x3e, 0x4b,
	0x63, 0x9f, 0x71, 0x2e, 0x14, 0x53, 0xb1, 0xe0, 0x59, 0xa9, 0x7a, 0x5f, 0xa1, 0xfd, 0x5e, 0x70,
	0x42, 0x84, 0x36, 0x67, 0x97, 0x64, 0x1b, 0xae, 0x31, 0xde, 0x0f, 0x8a, 0x6f, 0x7c, 0x0e, 0x7b,
	0x92, 0x2d, 0x62, 0xa6, 0x84, 0xb4, 0x4d, 0xb7, 0x35, 0xee, 0x4d, 0xac, 0xd3, 0x9a, 0x1d, 0x54,
	0x42, 0xd0, 0x58, 0xb4, 0x3d, 0x9b, 0x7f, 0xa6, 0x45, 0x9e, 0x90, 0xdd, 0x72, 0x8d, 0x35, 0x7b,
	0x58, 0x09, 0x41, 0x63, 0xf1, 0x2c, 0x18, 0x5c, 0x90, 0xd2, 0xc5, 0xb3, 0x80, 0xbe, 0xe4, 0x94,
	0x29, 0x6f, 0x02, 0xfd, 0xe5, 0x51, 0x9a, 0x5c, 0xe3, 0x53, 0x68, 0xdf, 0x08, 0xae, 0xbb, 0xd2,
	0xd5, 0xfb, 0x0d, 0x4e, 0x5b, 0x82, 0x42, 0xf2, 0x8e, 0xe1, 0xa0, 0xba, 0x13, 0x2a, 0xa6, 0xf2,
	0x9a, 0xb5, 0x6d, 0x20, 0xef, 0xd6, 0x00, 0xdc, 0x30, 0xeb, 0x2a, 0xdb, 0x67, 0x47, 0xc5, 0x64,
	0x44, 0xea, 0x83, 0xa2, 0xcb, 0x94, 0x24, 0x53, 0xb9, 0x24, 0xdb, 0x74, 0x8d, 0xb1, 0x19, 0x58,
	0xa5, 0xf2, 0x66, 0x29, 0xa0, 0x0f, 0x0f, 0xe6, 0xb9, 0x94, 0xc4, 0xd7, 0xfd, 0xad, 0xc2, 0x8f,
	0x95, 0xb4, 0x7a, 0xe1, 0x04, 0x76, 0x33, 0xc5, 0x14, 0xd9, 0x6d, 0xd7, 0x18, 0xff, 0x3f, 0x39,
	0x6c, 0x46, 0x7b, 0x45, 0x4c, 0xc5, 0x3c, 0xd2, 0xfd, 0x51, 0x50, 0x7a, 0xd6, 0x36, 0xbb, 0x7b,
	0xff, 0x66, 0x2f, 0x60, 0x14, 0x56, 0x53, 0xd6, 0x62, 0xb5, 0x94, 0x55, 0x90, 0x71, 0x3f, 0x68,
	0x04, 0x07, 0x7f, 0x81, 0xd2, 0xe4, 0xda, 0x3b, 0x81, 0xce, 0x99, 0xe0, 0x9f, 0xe2, 0xe8, 0x1f,
	0x1e, 0xe8, 0xf8, 0x19, 0xfc, 0xb7, 0x3a, 0x13, 0xf6, 0xa0, 0xfb, 0x76, 0xfa, 0x7a, 0x3a, 0x7b,
	0x37, 0x1d, 0xee, 0x60, 0x07, 0xcc, 0xd9, 0x74, 0x68, 0x60, 0x17, 0x5a, 0xb3, 0xf3, 0xf3, 0xa1,
	0x39, 0xf9, 0x65, 0xc2, 0x61, 0x65, 0x3f, 0x2b, 0x59, 0x61, 0x99, 0x72, 0x9c, 0xc1, 0x5e, 0x1d,
	0x0e, 0xb4, 0x9b, 0x42, 0x1b, 0x11, 0x72, 0x46, 0x5b, 0x14, 0xdd, 0xb2, 0xf5, 0xe3, 0xf7, 0xed,
	0x4f, 0xb3, 0x87, 0xfb, 0xfe, 0xd5, 0x0b, 0xff, 0xa6, 0x80, 0x2c, 0x9a, 0xb4, 0x95, 0x61, 0xc0,
	0xa3, 0xcd, 0xbb, 0x6b, 0x89, 0x72, 0x1e, 0xdd, 0x25, 0x6b, 0xfe, 0xc3, 0x82, 0x6f, 0xe1, 0xa0,
	0xe6, 0xfb, 0xdf, 0x74, 0x8e, 0xbe, 0x63, 0x08, 0x83, 0x8d, 0x1d, 0xe2, 0x93, 0xe5, 0xce, 0xb7,
	0x3e, 0x93, 0x73, 0x74, 0xb7, 0x41, 0xd7, 0xda, 0xf9, 0xd8, 0x29, 0x7e, 0xde, 0x97, 0x7f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x73, 0x57, 0x16, 0x6e, 0x03, 0x04, 0x00, 0x00,
}
